name: counter
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.3.10'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ansicolor: ^2.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  go_router: ^6.0.1
  flutter_native_splash: ^2.2.16
  dart_jsonwebtoken: ^2.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  jwt_decode: ^0.3.1
  sqflite: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter_native_splash:
#   color: "#000000"
#   image: assets/images/splash.png  
#   branding: assets/images/branding.png
#   android: true
#   ios: true
#   web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    # - assets/images/splash.png
    # - assets/images/branding.png
    - assets/database/counters.sql
    